# black
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=100
          - --include='\.pyi?$'

          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""

        language_version: python3.9.7
